In [2]:
import pandas as pd

In [3]:
import matplotlib.pyplot as plt

In [4]:
%matplotlib inline

In [5]:
df = pd.read_csv("data/season_1/groupby_all.csv")

In [6]:
df.dtypes

start_district_num      int64
time_slice              int64
date                   object
order_count           float64
succeed_count         float64
gap                   float64
dtype: object

In [22]:
df[["start_district_num", "time_slice", "order_count", 'succeed_count', 'gap']] = \
df[["start_district_num", "time_slice","order_count", 'succeed_count', 'gap']].\
    apply(lambda x: pd.to_numeric(x, errors='coerce'))
    
# transfer object to numbers

In [7]:
df["date"] = df["date"].apply(lambda x: pd.to_datetime(x, errors='coerce'))

In [8]:
df.dtypes

start_district_num             int64
time_slice                     int64
date                  datetime64[ns]
order_count                  float64
succeed_count                float64
gap                          float64
dtype: object

In [9]:
df

,start_district_num,time_slice,date,order_count,succeed_count,gap
0,1,1,2016-01-01,187.0,178.0,9.0
1,1,2,2016-01-01,198.0,191.0,7.0
2,1,3,2016-01-01,192.0,182.0,10.0
3,1,4,2016-01-01,172.0,167.0,5.0
4,1,5,2016-01-01,153.0,152.0,1.0
5,1,6,2016-01-01,132.0,131.0,1.0
6,1,7,2016-01-01,133.0,127.0,6.0
7,1,8,2016-01-01,130.0,128.0,2.0
8,1,9,2016-01-01,120.0,114.0,6.0
9,1,10,2016-01-01,111.0,105.0,6.0
10,1,11,2016-01-01,72.0,70.0,2.0
11,1,12,2016-01-01,73.0,70.0,3.0
12,1,13,2016-01-01,61.0,60.0,1.0
13,1,14,2016-01-01,71.0,67.0,4.0
14,1,15,2016-01-01,59.0,56.0,3.0
15,1,16,2016-01-01,84.0,73.0,11.0
16,1,17,2016-01-01,73.0,53.0,20.0
17,1,18,2016-01-01,65.0,47.0,18.0
18,1,19,2016-01-01,61.0,50.0,11.0
19,1,20,2016-01-01,46.0,40.0,6.0
20,1,21,2016-01-01,41.0,39.0,2.0
21,1,22,2016-01-01,32.0,31.0,1.0
22,1,23,2016-01-01,40.0,37.0,3.0
23,1,24,2016-01-01,30.0,22.0,8.0
24,1,25,2016-01-01,18.0,17.0,1.0
25,1,26,2016-01-01,24.0,23.0,1.0
26,1,27,2016-01-01,29.0,24.0,5.0
27,1,28,2016-01-01,16.0,16.0,0.0
28,1,29,2016-01-01,21.0,17.0,4.0
29,1,30,2016-01-01,25.0,12.0,13.0
...,...,...,...,...,...,...
294594,66,115,2016-01-31,20.0,20.0,0.0
294595,66,116,2016-01-31,22.0,22.0,0.0
294596,66,117,2016-01-31,24.0,24.0,0.0
294597,66,118,2016-01-31,0.0,0.0,0.0
294598,66,119,2016-01-31,0.0,0.0,0.0
294599,66,120,2016-01-31,0.0,0.0,0.0
294600,66,121,2016-01-31,0.0,0.0,0.0
294601,66,122,2016-01-31,0.0,0.0,0.0
294602,66,123,2016-01-31,0.0,0.0,0.0
294603,66,124,2016-01-31,0.0,0.0,0.0
294604,66,125,2016-01-31,0.0,0.0,0.0
294605,66,126,2016-01-31,0.0,0.0,0.0
294606,66,127,2016-01-31,17.0,17.0,0.0
294607,66,128,2016-01-31,13.0,13.0,0.0
294608,66,129,2016-01-31,18.0,18.0,0.0
294609,66,130,2016-01-31,0.0,0.0,0.0
294610,66,131,2016-01-31,0.0,0.0,0.0
294611,66,132,2016-01-31,0.0,0.0,0.0
294612,66,133,2016-01-31,0.0,0.0,0.0
294613,66,134,2016-01-31,0.0,0.0,0.0
294614,66,135,2016-01-31,0.0,0.0,0.0
294615,66,136,2016-01-31,0.0,0.0,0.0
294616,66,137,2016-01-31,0.0,0.0,0.0
294617,66,138,2016-01-31,0.0,0.0,0.0
294618,66,139,2016-01-31,10.0,10.0,0.0
294619,66,140,2016-01-31,4.0,4.0,0.0
294620,66,141,2016-01-31,9.0,9.0,0.0
294621,66,142,2016-01-31,0.0,0.0,0.0
294622,66,143,2016-01-31,0.0,0.0,0.0
294623,66,144,2016-01-31,0.0,0.0,0.0

In [10]:
from sklearn.metrics.scorer import make_scorer
import math

def MAPE_scorer(y, y_pred):
    error = 0
    num = len(y)
    for i in range(0, num):
        if y[i] > 0:
            error += math.fabs(y_pred[i] - y[i]) / y[i]
    print(error, num)
    if num > 0:
        return error / num
    else:
        return 0

my_scorer = make_scorer(MAPE_scorer)

In [11]:
y = df['gap'][:21*66*144]
MAPE_scorer(y, [1 for i in range(0, 21*66*144)])

53370.3598616 199584

0.26740800796433484

In [12]:
df_predict = df.loc[df['time_slice'].isin([46, 58, 70, 82, 94, 106, 118, 130, 142])]

df_predict

,start_district_num,time_slice,date,order_count,succeed_count,gap
45,1,46,2016-01-01,129.0,125.0,4.0
57,1,58,2016-01-01,150.0,146.0,4.0
69,1,70,2016-01-01,201.0,186.0,15.0
81,1,82,2016-01-01,225.0,207.0,18.0
93,1,94,2016-01-01,224.0,222.0,2.0
105,1,106,2016-01-01,290.0,279.0,11.0
117,1,118,2016-01-01,214.0,205.0,9.0
129,1,130,2016-01-01,234.0,226.0,8.0
141,1,142,2016-01-01,115.0,111.0,4.0
189,2,46,2016-01-01,11.0,11.0,0.0
201,2,58,2016-01-01,17.0,16.0,1.0
213,2,70,2016-01-01,22.0,22.0,0.0
225,2,82,2016-01-01,26.0,24.0,2.0
237,2,94,2016-01-01,21.0,20.0,1.0
249,2,106,2016-01-01,22.0,21.0,1.0
261,2,118,2016-01-01,29.0,29.0,0.0
273,2,130,2016-01-01,23.0,22.0,1.0
285,2,142,2016-01-01,16.0,16.0,0.0
333,3,46,2016-01-01,6.0,2.0,4.0
345,3,58,2016-01-01,3.0,1.0,2.0
357,3,70,2016-01-01,4.0,2.0,2.0
369,3,82,2016-01-01,3.0,3.0,0.0
381,3,94,2016-01-01,6.0,6.0,0.0
393,3,106,2016-01-01,4.0,4.0,0.0
405,3,118,2016-01-01,3.0,3.0,0.0
417,3,130,2016-01-01,3.0,3.0,0.0
429,3,142,2016-01-01,2.0,1.0,1.0
477,4,46,2016-01-01,44.0,20.0,24.0
489,4,58,2016-01-01,49.0,31.0,18.0
501,4,70,2016-01-01,105.0,41.0,64.0
...,...,...,...,...,...,...
294165,63,118,2016-01-31,0.0,0.0,0.0
294177,63,130,2016-01-31,0.0,0.0,0.0
294189,63,142,2016-01-31,0.0,0.0,0.0
294237,64,46,2016-01-31,0.0,0.0,0.0
294249,64,58,2016-01-31,0.0,0.0,0.0
294261,64,70,2016-01-31,0.0,0.0,0.0
294273,64,82,2016-01-31,0.0,0.0,0.0
294285,64,94,2016-01-31,0.0,0.0,0.0
294297,64,106,2016-01-31,0.0,0.0,0.0
294309,64,118,2016-01-31,0.0,0.0,0.0
294321,64,130,2016-01-31,0.0,0.0,0.0
294333,64,142,2016-01-31,0.0,0.0,0.0
294381,65,46,2016-01-31,0.0,0.0,0.0
294393,65,58,2016-01-31,0.0,0.0,0.0
294405,65,70,2016-01-31,0.0,0.0,0.0
294417,65,82,2016-01-31,0.0,0.0,0.0
294429,65,94,2016-01-31,0.0,0.0,0.0
294441,65,106,2016-01-31,0.0,0.0,0.0
294453,65,118,2016-01-31,0.0,0.0,0.0
294465,65,130,2016-01-31,0.0,0.0,0.0
294477,65,142,2016-01-31,0.0,0.0,0.0
294525,66,46,2016-01-31,0.0,0.0,0.0
294537,66,58,2016-01-31,0.0,0.0,0.0
294549,66,70,2016-01-31,0.0,0.0,0.0
294561,66,82,2016-01-31,0.0,0.0,0.0
294573,66,94,2016-01-31,0.0,0.0,0.0
294585,66,106,2016-01-31,0.0,0.0,0.0
294597,66,118,2016-01-31,0.0,0.0,0.0
294609,66,130,2016-01-31,0.0,0.0,0.0
294621,66,142,2016-01-31,0.0,0.0,0.0

In [13]:
# y baseline by all 1
y_train = df_predict['gap'][:9*21*66].as_matrix() # transform to np.array

MAPE_scorer(y_train, [1 for i in range(0, len(y_train))])

3854.59133608 12474

0.30901004778565

In [16]:
df['weekday'] = df['date'].dt.weekday

In [18]:
df['is_holiday'] = df['weekday'] - df['weekday']

In [24]:
df[df.date=='2016-01-01']['is_holiday'] = 1

/Users/mofrankhu/.pyenv/versions/3.5.1/Python.framework/Versions/3.5/lib/python3.5/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [26]:
df.to_csv('features1.csv')

In [27]:
df1 = pd.read_csv('features1.csv')

In [28]:
df1.dtypes()

Unnamed: 0             int64
start_district_num     int64
time_slice             int64
date                  object
order_count            int64
succeed_count          int64
gap                    int64
weekday                int64
is_holiday             int64
dtype: object

In [29]:
df1["date"] = df1["date"].apply(lambda x: pd.to_datetime(x, errors='coerce'))

In [33]:
df1[["order_count", 'succeed_count', 'gap']] = \
df1[["order_count", 'succeed_count', 'gap']].astype(float)
# transfer object to numbers

In [34]:
df1

,Unnamed: 0,start_district_num,time_slice,date,order_count,succeed_count,gap,weekday,is_holiday
0,0,1,1,2016-01-01,187.0,178.0,9.0,4,1
1,1,1,2,2016-01-01,198.0,191.0,7.0,4,1
2,2,1,3,2016-01-01,192.0,182.0,10.0,4,1
3,3,1,4,2016-01-01,172.0,167.0,5.0,4,1
4,4,1,5,2016-01-01,153.0,152.0,1.0,4,1
5,5,1,6,2016-01-01,132.0,131.0,1.0,4,1
6,6,1,7,2016-01-01,133.0,127.0,6.0,4,1
7,7,1,8,2016-01-01,130.0,128.0,2.0,4,1
8,8,1,9,2016-01-01,120.0,114.0,6.0,4,1
9,9,1,10,2016-01-01,111.0,105.0,6.0,4,1
10,10,1,11,2016-01-01,72.0,70.0,2.0,4,1
11,11,1,12,2016-01-01,73.0,70.0,3.0,4,1
12,12,1,13,2016-01-01,61.0,60.0,1.0,4,1
13,13,1,14,2016-01-01,71.0,67.0,4.0,4,1
14,14,1,15,2016-01-01,59.0,56.0,3.0,4,1
15,15,1,16,2016-01-01,84.0,73.0,11.0,4,1
16,16,1,17,2016-01-01,73.0,53.0,20.0,4,1
17,17,1,18,2016-01-01,65.0,47.0,18.0,4,1
18,18,1,19,2016-01-01,61.0,50.0,11.0,4,1
19,19,1,20,2016-01-01,46.0,40.0,6.0,4,1
20,20,1,21,2016-01-01,41.0,39.0,2.0,4,1
21,21,1,22,2016-01-01,32.0,31.0,1.0,4,1
22,22,1,23,2016-01-01,40.0,37.0,3.0,4,1
23,23,1,24,2016-01-01,30.0,22.0,8.0,4,1
24,24,1,25,2016-01-01,18.0,17.0,1.0,4,1
25,25,1,26,2016-01-01,24.0,23.0,1.0,4,1
26,26,1,27,2016-01-01,29.0,24.0,5.0,4,1
27,27,1,28,2016-01-01,16.0,16.0,0.0,4,1
28,28,1,29,2016-01-01,21.0,17.0,4.0,4,1
29,29,1,30,2016-01-01,25.0,12.0,13.0,4,1
...,...,...,...,...,...,...,...,...,...
294594,294594,66,115,2016-01-31,20.0,20.0,0.0,6,0
294595,294595,66,116,2016-01-31,22.0,22.0,0.0,6,0
294596,294596,66,117,2016-01-31,24.0,24.0,0.0,6,0
294597,294597,66,118,2016-01-31,0.0,0.0,0.0,6,0
294598,294598,66,119,2016-01-31,0.0,0.0,0.0,6,0
294599,294599,66,120,2016-01-31,0.0,0.0,0.0,6,0
294600,294600,66,121,2016-01-31,0.0,0.0,0.0,6,0
294601,294601,66,122,2016-01-31,0.0,0.0,0.0,6,0
294602,294602,66,123,2016-01-31,0.0,0.0,0.0,6,0
294603,294603,66,124,2016-01-31,0.0,0.0,0.0,6,0
294604,294604,66,125,2016-01-31,0.0,0.0,0.0,6,0
294605,294605,66,126,2016-01-31,0.0,0.0,0.0,6,0
294606,294606,66,127,2016-01-31,17.0,17.0,0.0,6,0
294607,294607,66,128,2016-01-31,13.0,13.0,0.0,6,0
294608,294608,66,129,2016-01-31,18.0,18.0,0.0,6,0
294609,294609,66,130,2016-01-31,0.0,0.0,0.0,6,0
294610,294610,66,131,2016-01-31,0.0,0.0,0.0,6,0
294611,294611,66,132,2016-01-31,0.0,0.0,0.0,6,0
294612,294612,66,133,2016-01-31,0.0,0.0,0.0,6,0
294613,294613,66,134,2016-01-31,0.0,0.0,0.0,6,0
294614,294614,66,135,2016-01-31,0.0,0.0,0.0,6,0
294615,294615,66,136,2016-01-31,0.0,0.0,0.0,6,0
294616,294616,66,137,2016-01-31,0.0,0.0,0.0,6,0
294617,294617,66,138,2016-01-31,0.0,0.0,0.0,6,0
294618,294618,66,139,2016-01-31,10.0,10.0,0.0,6,0
294619,294619,66,140,2016-01-31,4.0,4.0,0.0,6,0
294620,294620,66,141,2016-01-31,9.0,9.0,0.0,6,0
294621,294621,66,142,2016-01-31,0.0,0.0,0.0,6,0
294622,294622,66,143,2016-01-31,0.0,0.0,0.0,6,0
294623,294623,66,144,2016-01-31,0.0,0.0,0.0,6,0

In [40]:
df_train_1 = df1[df.start_district_num == 1][df.date < '2016-01-22']
df_test_1 = df1[df.start_district_num == 1][df.date > '2016-01-21']

/Users/mofrankhu/.pyenv/versions/3.5.1/Python.framework/Versions/3.5/lib/python3.5/site-packages/ipykernel/__main__.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  if __name__ == '__main__':
/Users/mofrankhu/.pyenv/versions/3.5.1/Python.framework/Versions/3.5/lib/python3.5/site-packages/ipykernel/__main__.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  from ipykernel import kernelapp as app

In [39]:
df_train_1

,Unnamed: 0,start_district_num,time_slice,date,order_count,succeed_count,gap,weekday,is_holiday
0,0,1,1,2016-01-01,187.0,178.0,9.0,4,1
1,1,1,2,2016-01-01,198.0,191.0,7.0,4,1
2,2,1,3,2016-01-01,192.0,182.0,10.0,4,1
3,3,1,4,2016-01-01,172.0,167.0,5.0,4,1
4,4,1,5,2016-01-01,153.0,152.0,1.0,4,1
5,5,1,6,2016-01-01,132.0,131.0,1.0,4,1
6,6,1,7,2016-01-01,133.0,127.0,6.0,4,1
7,7,1,8,2016-01-01,130.0,128.0,2.0,4,1
8,8,1,9,2016-01-01,120.0,114.0,6.0,4,1
9,9,1,10,2016-01-01,111.0,105.0,6.0,4,1
10,10,1,11,2016-01-01,72.0,70.0,2.0,4,1
11,11,1,12,2016-01-01,73.0,70.0,3.0,4,1
12,12,1,13,2016-01-01,61.0,60.0,1.0,4,1
13,13,1,14,2016-01-01,71.0,67.0,4.0,4,1
14,14,1,15,2016-01-01,59.0,56.0,3.0,4,1
15,15,1,16,2016-01-01,84.0,73.0,11.0,4,1
16,16,1,17,2016-01-01,73.0,53.0,20.0,4,1
17,17,1,18,2016-01-01,65.0,47.0,18.0,4,1
18,18,1,19,2016-01-01,61.0,50.0,11.0,4,1
19,19,1,20,2016-01-01,46.0,40.0,6.0,4,1
20,20,1,21,2016-01-01,41.0,39.0,2.0,4,1
21,21,1,22,2016-01-01,32.0,31.0,1.0,4,1
22,22,1,23,2016-01-01,40.0,37.0,3.0,4,1
23,23,1,24,2016-01-01,30.0,22.0,8.0,4,1
24,24,1,25,2016-01-01,18.0,17.0,1.0,4,1
25,25,1,26,2016-01-01,24.0,23.0,1.0,4,1
26,26,1,27,2016-01-01,29.0,24.0,5.0,4,1
27,27,1,28,2016-01-01,16.0,16.0,0.0,4,1
28,28,1,29,2016-01-01,21.0,17.0,4.0,4,1
29,29,1,30,2016-01-01,25.0,12.0,13.0,4,1
...,...,...,...,...,...,...,...,...,...
190194,190194,1,115,2016-01-21,214.0,211.0,3.0,3,0
190195,190195,1,116,2016-01-21,199.0,195.0,4.0,3,0
190196,190196,1,117,2016-01-21,230.0,221.0,9.0,3,0
190197,190197,1,118,2016-01-21,199.0,195.0,4.0,3,0
190198,190198,1,119,2016-01-21,188.0,181.0,7.0,3,0
190199,190199,1,120,2016-01-21,188.0,182.0,6.0,3,0
190200,190200,1,121,2016-01-21,239.0,235.0,4.0,3,0
190201,190201,1,122,2016-01-21,279.0,274.0,5.0,3,0
190202,190202,1,123,2016-01-21,240.0,235.0,5.0,3,0
190203,190203,1,124,2016-01-21,263.0,252.0,11.0,3,0
190204,190204,1,125,2016-01-21,224.0,218.0,6.0,3,0
190205,190205,1,126,2016-01-21,252.0,247.0,5.0,3,0
190206,190206,1,127,2016-01-21,270.0,263.0,7.0,3,0
190207,190207,1,128,2016-01-21,252.0,246.0,6.0,3,0
190208,190208,1,129,2016-01-21,197.0,191.0,6.0,3,0
190209,190209,1,130,2016-01-21,202.0,195.0,7.0,3,0
190210,190210,1,131,2016-01-21,195.0,192.0,3.0,3,0
190211,190211,1,132,2016-01-21,186.0,181.0,5.0,3,0
190212,190212,1,133,2016-01-21,191.0,186.0,5.0,3,0
190213,190213,1,134,2016-01-21,158.0,149.0,9.0,3,0
190214,190214,1,135,2016-01-21,130.0,126.0,4.0,3,0
190215,190215,1,136,2016-01-21,133.0,130.0,3.0,3,0
190216,190216,1,137,2016-01-21,113.0,111.0,2.0,3,0
190217,190217,1,138,2016-01-21,109.0,106.0,3.0,3,0
190218,190218,1,139,2016-01-21,76.0,73.0,3.0,3,0
190219,190219,1,140,2016-01-21,67.0,63.0,4.0,3,0
190220,190220,1,141,2016-01-21,77.0,69.0,8.0,3,0
190221,190221,1,142,2016-01-21,70.0,66.0,4.0,3,0
190222,190222,1,143,2016-01-21,50.0,47.0,3.0,3,0
190223,190223,1,144,2016-01-21,61.0,52.0,9.0,3,0

In [41]:
df_test_1

,Unnamed: 0,start_district_num,time_slice,date,order_count,succeed_count,gap,weekday,is_holiday
199584,199584,1,1,2016-01-22,0.0,0.0,0.0,4,0
199585,199585,1,2,2016-01-22,0.0,0.0,0.0,4,0
199586,199586,1,3,2016-01-22,0.0,0.0,0.0,4,0
199587,199587,1,4,2016-01-22,0.0,0.0,0.0,4,0
199588,199588,1,5,2016-01-22,0.0,0.0,0.0,4,0
199589,199589,1,6,2016-01-22,0.0,0.0,0.0,4,0
199590,199590,1,7,2016-01-22,0.0,0.0,0.0,4,0
199591,199591,1,8,2016-01-22,0.0,0.0,0.0,4,0
199592,199592,1,9,2016-01-22,0.0,0.0,0.0,4,0
199593,199593,1,10,2016-01-22,0.0,0.0,0.0,4,0
199594,199594,1,11,2016-01-22,0.0,0.0,0.0,4,0
199595,199595,1,12,2016-01-22,0.0,0.0,0.0,4,0
199596,199596,1,13,2016-01-22,0.0,0.0,0.0,4,0
199597,199597,1,14,2016-01-22,0.0,0.0,0.0,4,0
199598,199598,1,15,2016-01-22,0.0,0.0,0.0,4,0
199599,199599,1,16,2016-01-22,0.0,0.0,0.0,4,0
199600,199600,1,17,2016-01-22,0.0,0.0,0.0,4,0
199601,199601,1,18,2016-01-22,0.0,0.0,0.0,4,0
199602,199602,1,19,2016-01-22,0.0,0.0,0.0,4,0
199603,199603,1,20,2016-01-22,0.0,0.0,0.0,4,0
199604,199604,1,21,2016-01-22,0.0,0.0,0.0,4,0
199605,199605,1,22,2016-01-22,0.0,0.0,0.0,4,0
199606,199606,1,23,2016-01-22,0.0,0.0,0.0,4,0
199607,199607,1,24,2016-01-22,0.0,0.0,0.0,4,0
199608,199608,1,25,2016-01-22,0.0,0.0,0.0,4,0
199609,199609,1,26,2016-01-22,0.0,0.0,0.0,4,0
199610,199610,1,27,2016-01-22,0.0,0.0,0.0,4,0
199611,199611,1,28,2016-01-22,0.0,0.0,0.0,4,0
199612,199612,1,29,2016-01-22,0.0,0.0,0.0,4,0
199613,199613,1,30,2016-01-22,0.0,0.0,0.0,4,0
...,...,...,...,...,...,...,...,...,...
285234,285234,1,115,2016-01-31,257.0,248.0,9.0,6,0
285235,285235,1,116,2016-01-31,274.0,243.0,31.0,6,0
285236,285236,1,117,2016-01-31,265.0,218.0,47.0,6,0
285237,285237,1,118,2016-01-31,0.0,0.0,0.0,6,0
285238,285238,1,119,2016-01-31,0.0,0.0,0.0,6,0
285239,285239,1,120,2016-01-31,0.0,0.0,0.0,6,0
285240,285240,1,121,2016-01-31,0.0,0.0,0.0,6,0
285241,285241,1,122,2016-01-31,0.0,0.0,0.0,6,0
285242,285242,1,123,2016-01-31,0.0,0.0,0.0,6,0
285243,285243,1,124,2016-01-31,0.0,0.0,0.0,6,0
285244,285244,1,125,2016-01-31,0.0,0.0,0.0,6,0
285245,285245,1,126,2016-01-31,0.0,0.0,0.0,6,0
285246,285246,1,127,2016-01-31,267.0,231.0,36.0,6,0
285247,285247,1,128,2016-01-31,242.0,227.0,15.0,6,0
285248,285248,1,129,2016-01-31,261.0,247.0,14.0,6,0
285249,285249,1,130,2016-01-31,0.0,0.0,0.0,6,0
285250,285250,1,131,2016-01-31,0.0,0.0,0.0,6,0
285251,285251,1,132,2016-01-31,0.0,0.0,0.0,6,0
285252,285252,1,133,2016-01-31,0.0,0.0,0.0,6,0
285253,285253,1,134,2016-01-31,0.0,0.0,0.0,6,0
285254,285254,1,135,2016-01-31,0.0,0.0,0.0,6,0
285255,285255,1,136,2016-01-31,0.0,0.0,0.0,6,0
285256,285256,1,137,2016-01-31,0.0,0.0,0.0,6,0
285257,285257,1,138,2016-01-31,0.0,0.0,0.0,6,0
285258,285258,1,139,2016-01-31,59.0,55.0,4.0,6,0
285259,285259,1,140,2016-01-31,62.0,57.0,5.0,6,0
285260,285260,1,141,2016-01-31,68.0,65.0,3.0,6,0
285261,285261,1,142,2016-01-31,0.0,0.0,0.0,6,0
285262,285262,1,143,2016-01-31,0.0,0.0,0.0,6,0
285263,285263,1,144,2016-01-31,0.0,0.0,0.0,6,0

In [46]:
X = df_train_1.as_matrix(columns=['time_slice','order_count','succeed_count',
                                  'weekday', 'is_holiday'])
y = df_train_1.as_matrix(columns=['gap']).ravel()

In [45]:
X

array([[   1.,  187.,  178.,    4.,    1.],
       [   2.,  198.,  191.,    4.,    1.],
       [   3.,  192.,  182.,    4.,    1.],
       ...,
       [ 142.,   70.,   66.,    3.,    0.],
       [ 143.,   50.,   47.,    3.,    0.],
       [ 144.,   61.,   52.,    3.,    0.]])

In [47]:
from sklearn.ensemble import RandomForestRegressor
from sklearn import cross_validation

X_train, X_test, y_train, y_test = cross_validation.train_test_split(
    X, y, test_size=0.2, random_state=0)

clf = RandomForestRegressor(n_estimators=5)
clf = clf.fit(X_train, y_train)

print(clf.score(X_train, y_train))
print(clf.score(X_test, y_test))

0.960155059138
0.905648910855

In [52]:
from sklearn.cross_validation import cross_val_score

from sklearn.metrics.scorer import make_scorer
import math

def MAPE_scorer(y, y_pred):
    error = 0
    num = len(y)
    for i in range(0, num):
        if y[i] > 0:
            error += math.fabs(y_pred[i] - y[i]) / y[i]
    print(error, num)
    if num > 0:
        return error / num
    else:
        return 0

my_scorer = make_scorer(MAPE_scorer)

cross_val_score(clf, X=X_test, y=y_test, scoring=my_scorer, cv=None, n_jobs=1, verbose=0, fit_params=None, 
                pre_dispatch='2*n_jobs')

113.025382506 202
110.505622896 202
115.930189563 201

array([ 0.5595316 ,  0.54705754,  0.57676711])

In [57]:
#print(clf.predict(X_test))
#print(y_test)
print(MAPE_scorer(y_train, clf.predict(X_train)))
print(MAPE_scorer(y_test, clf.predict(X_test)))

346.95418172 2419
0.143428764663
185.067771974 605
0.305897143758

In [61]:
df_NB = df1[df1['time_slice'].isin([46,58,70,82,94,106,118,130,142])][df.date < '2016-01-22']\
    [df.date > '2016-01-01']
# exclude 0101 and then NB

/Users/mofrankhu/.pyenv/versions/3.5.1/Python.framework/Versions/3.5/lib/python3.5/site-packages/ipykernel/__main__.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  if __name__ == '__main__':

In [62]:
df_NB

,Unnamed: 0,start_district_num,time_slice,date,order_count,succeed_count,gap,weekday,is_holiday
9549,9549,1,46,2016-01-02,66.0,66.0,0.0,5,1
9561,9561,1,58,2016-01-02,102.0,97.0,5.0,5,1
9573,9573,1,70,2016-01-02,125.0,121.0,4.0,5,1
9585,9585,1,82,2016-01-02,178.0,171.0,7.0,5,1
9597,9597,1,94,2016-01-02,188.0,178.0,10.0,5,1
9609,9609,1,106,2016-01-02,280.0,272.0,8.0,5,1
9621,9621,1,118,2016-01-02,189.0,186.0,3.0,5,1
9633,9633,1,130,2016-01-02,232.0,217.0,15.0,5,1
9645,9645,1,142,2016-01-02,75.0,73.0,2.0,5,1
9693,9693,2,46,2016-01-02,10.0,10.0,0.0,5,1
9705,9705,2,58,2016-01-02,3.0,3.0,0.0,5,1
9717,9717,2,70,2016-01-02,25.0,24.0,1.0,5,1
9729,9729,2,82,2016-01-02,17.0,17.0,0.0,5,1
9741,9741,2,94,2016-01-02,21.0,20.0,1.0,5,1
9753,9753,2,106,2016-01-02,24.0,24.0,0.0,5,1
9765,9765,2,118,2016-01-02,20.0,20.0,0.0,5,1
9777,9777,2,130,2016-01-02,24.0,22.0,2.0,5,1
9789,9789,2,142,2016-01-02,6.0,6.0,0.0,5,1
9837,9837,3,46,2016-01-02,1.0,1.0,0.0,5,1
9849,9849,3,58,2016-01-02,4.0,4.0,0.0,5,1
9861,9861,3,70,2016-01-02,4.0,3.0,1.0,5,1
9873,9873,3,82,2016-01-02,8.0,5.0,3.0,5,1
9885,9885,3,94,2016-01-02,10.0,8.0,2.0,5,1
9897,9897,3,106,2016-01-02,2.0,2.0,0.0,5,1
9909,9909,3,118,2016-01-02,5.0,3.0,2.0,5,1
9921,9921,3,130,2016-01-02,6.0,5.0,1.0,5,1
9933,9933,3,142,2016-01-02,0.0,0.0,0.0,5,1
9981,9981,4,46,2016-01-02,20.0,18.0,2.0,5,1
9993,9993,4,58,2016-01-02,36.0,35.0,1.0,5,1
10005,10005,4,70,2016-01-02,58.0,49.0,9.0,5,1
...,...,...,...,...,...,...,...,...,...
199125,199125,63,118,2016-01-21,3.0,0.0,3.0,3,0
199137,199137,63,130,2016-01-21,0.0,0.0,0.0,3,0
199149,199149,63,142,2016-01-21,0.0,0.0,0.0,3,0
199197,199197,64,46,2016-01-21,17.0,16.0,1.0,3,0
199209,199209,64,58,2016-01-21,12.0,11.0,1.0,3,0
199221,199221,64,70,2016-01-21,16.0,16.0,0.0,3,0
199233,199233,64,82,2016-01-21,21.0,21.0,0.0,3,0
199245,199245,64,94,2016-01-21,14.0,14.0,0.0,3,0
199257,199257,64,106,2016-01-21,23.0,23.0,0.0,3,0
199269,199269,64,118,2016-01-21,13.0,13.0,0.0,3,0
199281,199281,64,130,2016-01-21,15.0,15.0,0.0,3,0
199293,199293,64,142,2016-01-21,7.0,7.0,0.0,3,0
199341,199341,65,46,2016-01-21,7.0,7.0,0.0,3,0
199353,199353,65,58,2016-01-21,3.0,3.0,0.0,3,0
199365,199365,65,70,2016-01-21,2.0,1.0,1.0,3,0
199377,199377,65,82,2016-01-21,4.0,3.0,1.0,3,0
199389,199389,65,94,2016-01-21,3.0,3.0,0.0,3,0
199401,199401,65,106,2016-01-21,9.0,6.0,3.0,3,0
199413,199413,65,118,2016-01-21,3.0,3.0,0.0,3,0
199425,199425,65,130,2016-01-21,1.0,1.0,0.0,3,0
199437,199437,65,142,2016-01-21,2.0,2.0,0.0,3,0
199485,199485,66,46,2016-01-21,23.0,23.0,0.0,3,0
199497,199497,66,58,2016-01-21,12.0,12.0,0.0,3,0
199509,199509,66,70,2016-01-21,14.0,14.0,0.0,3,0
199521,199521,66,82,2016-01-21,19.0,19.0,0.0,3,0
199533,199533,66,94,2016-01-21,14.0,13.0,1.0,3,0
199545,199545,66,106,2016-01-21,24.0,24.0,0.0,3,0
199557,199557,66,118,2016-01-21,27.0,27.0,0.0,3,0
199569,199569,66,130,2016-01-21,9.0,9.0,0.0,3,0
199581,199581,66,142,2016-01-21,6.0,6.0,0.0,3,0

In [69]:
df_NB = df_NB.groupby(['start_district_num','time_slice','weekday']).mean()[['gap']]

In [71]:
df_NB.to_csv('20160613.csv')